version: '3'

services:
  squid:
    image: datadog/squid
    container_name: squid
    restart: always
    ports:
      - 80:3128
      - 443:3129
    volumes:
      - ./squid/cache:/var/spool/squid
      - ./squid/logs:/var/log/squid
      - ./squid.conf:/etc/squid/squid.conf
      - ./passwords:/etc/squid/passwords
      - ./bad-sites.acl:/etc/squid/bad-sites.acl
